# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3718e09580d847c7f2f6c656f275cfb2be2b6da0e9f1cb55ea0326ca5e3dd360e7ef489fc39159ed3dc955817e205c9ab2c5553aae1a8f53681718105f3756df

test:
  secret_key_base: 70f42b0f502f3b4473b52b649107752fc80a83c221de385b04f9416f39291d1d11fda5901fa246fb7673772c004cb31fc909263cb4a68f4210237c48b594dc19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
